version: '3.9'
services:
  # Serviço para executar a aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - backend

  # Serviço para executar o Postgres
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    restart: 'always'
    networks:
      - backend

networks:
  backend: